colorScheme = "avocado"
defaultAppearance = "light" 
autoSwitchAppearance = true

enableA11y = false
enableSearch = false
enableStyledScrollbar = true
replyByEmail = false

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false

defaultBackgroundImage = "background.gif" # used as default for background images
defaultFeaturedImage = "background.gif"
# defaultSocialImage = "/android-chrome-512x512.png" # used as default for social media sharing (Open Graph and Twitter)
hotlinkFeatureImage = false
imagePosition = "50% 50%"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

fingerprintAlgorithm = "sha512" # Valid values are "sha512" (default), "sha384", "sha256"

giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = false
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true
  showSocialLinks = true    # <-- AÑADIDO: Muestra tus 3 iconos en el pie de página
  showAuthor = true         # <-- AÑADIDO: Asegura que el footer lea tus datos de autor

[homepage]
  layout = "card" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/background.gif" 
  showRecent = true
  showRecentItems = 3
  showMoreLink = false
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false
  disableHeroImageFilter = false # only used when layout equals hero

[article]
  showDate = false
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = false
  showAuthorBottom = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace
